### ISSUE TITLE
Naming of Outputs does not conform Angulars style guide

### ISSUE THREAD

**Issue by jase88** [chromaui/intro-storybook-angular-template#12]
[Style 05-16](https://angular.io/guide/styleguide#dont-prefix-output-properties): Don't prefix output properties

This also violates the eslint rule `@angular-eslint/no-output-on-prefix`.

**Suggestion**
On `button.component.ts`
- rename Output `onClick` and it's usages to `buttonClick`

On `header.component.ts`
- rename Output `onLogin` and it's usages to `login`
- rename Output `onLogout` and it's usages to `logout`
- rename Output `onCreateAccount` and it's usages to `createAccount`

**Comment by jonniebigodes** [comment]
Thanks for taking the time to reach out to us with your issue. We appreciate it. Sadly, I will close this as this is not a template issue per sé but rather a Storybook issue, as the template is only a consumer of Storybook. If you or anyone else is interested in following up with us and improving the examples, we encourage you to open up a [discussion](https://github.com/storybookjs/storybook/discussions/new/choose) and follow up with us maintainers so that it can be addressed. 

Hope you have a fantastic holiday season.

Stay safe
